const projects = [
  {
    id: 'maps',
    type: ['All', 'Web Dev'],
    src: 'neighborhood-maps.png',
    title: 'Neighborhood Maps',
    clickable: true,
    date: 'Nov 2018',
    client: 'Personal Project',
    brief:
      'Discover refreshment around every corner: Find a smoothie joint near you!',
    projDesc:
      'Maps is a smoothie locator with a predetermined list of smoothie shop locations in certain cities. This intermediate project teaches the ins and outs of React and how to use APIs. The planning of the project required a layout of the components and knowing which components rely on one another. The next problem was connecting the API to the map and getting the location pointers to match the geographical location.',
    skills: ['React', 'Google Maps API', 'Foursquare', 'MaterialUI'],
  },
  {
    id: 'reads',
    type: ['All', 'Web Dev'],
    src: 'my-reads.png',
    title: 'My Reads',
    clickable: true,
    date: 'Sep 2018',
    client: 'Personal Project',
    brief:
      'Your personalized digital bookshelf for empowering your reading journey.',
    projDesc:
      'My Reads allows a user to browse a digital library and add different books to their lists. The primary challenge was dynamically rendering content and working with query inputs.',
    skills: ['React'],
  },
  {
    id: 'mem',
    type: ['All', 'Web Dev'],
    src: 'memory-game.png',
    title: 'Memory Game',
    clickable: true,
    date: 'Aug 2018',
    client: 'Personal Project',
    brief: 'Flip. Remember. Match.',
    projDesc:
      'We all scream for better memory. No one likes to experience brain fog. Have fun with this mentally stimulating and sweet memory game.',
    skills: ['HTML5', 'CSS3', 'Javascript'],
  },
  {
    id: 'gm305',
    type: ['All', 'Motion'],
    title: 'GM Powertrain',
    clickable: true,
    date: 'Sep 2013',
    client: 'General Motors Powertrain | Continental Services',
    brief:
      'Having a cafe on the jobsite provides great benefits. Why not snag the best deals?',
    projDesc:
      'Nothing beats having a cafe inside the workplace. Digital menus are a great way to display regular prices and great deals at the same time. This digital menu was created as a way to increase sales by offering the best deals up front.',
    src: 'GM-Power-305x320.png',
    skills: ['After Effects', 'Digital Menu Board'],
  },
  {
    id: 'bala305',
    type: ['All', 'Print'],
    src: 'Balaboosta-305x320.png',
    title: 'Balaboosta',
    clickable: true,
    date: 'Nov 2013',
    client: 'Continental Services',
    brief: 'A mediterranian grill promo',
    projDesc: '',
    skills: ['Adobe CC', 'Branding', 'POS Marketing'],
  },
  {
    id: 'ed305',
    type: ['All', 'Print', 'Branding'],
    title: 'Educational Dining',
    clickable: true,
    date: 'Sep 2013',
    client: 'Educational Dining | Continental Services',
    brief:
      'Collateral pieces are a great way to leave behind important information for potiential clients.',
    projDesc: 'Branded collateral pieces',
    src: 'Ed-Dining-305x320.png',
    skills: ['Adobe CC', 'Marketing'],
  },
  {
    id: 'cont305',
    type: ['All', 'Motion'],
    title: 'Client Movie',
    clickable: true,
    date: 'Feb 2014',
    client: 'Continental Serivces',
    brief: 'A digital display of services offered under various subsidaries.',
    projDesc: '',
    src: 'Cont-Client-305x320.png',
    skills: ['After Effects'],
  },
  {
    id: 'luc305',
    type: ['All', 'Motion'],
    title: 'Lucca | Italian Street Food',
    clickable: true,
    date: 'Jan 2014',
    client: 'Continental Services',
    brief: 'An Italian street food promo.',
    projDesc: '',
    src: 'Lucca-305x320.png',
    skills: ['After Effects', 'Digital Menu Board'],
  },
  {
    id: 'rof305',
    type: ['All', 'Print'],
    src: 'Rise-of-Fall-305x320.png',
    title: 'The Rise of Fall Pasta',
    clickable: true,
    date: 'Oct 2013',
    client: 'Continental Services',
    brief: 'A comfort food promo.',
    projDesc: '',
    skills: ['Adobe CC', 'Marketing'],
  },
  {
    id: 'ap305',
    type: ['All', 'Print', 'Branding'],
    title: 'Portfolio Magazine',
    clickable: true,
    date: 'May 2013',
    client: 'Andre Morton | I AM Creative LLC',
    brief: 'Collaborative graduation portfolio project',
    projDesc:
      'As a part of portfolio show, students have to showcase their work. With aspirations of being a creative director, I had the opportunity to be under his direction. I was given an idea of what the content and topics would be and we went out and took photos based off of those concepts. After that, we began strategizing the order and layout of the piece.',
    src: 'Andre-Port-305x320.png',
    skills: ['Adobe CC', 'Photography', 'Print Design'],
  },
  {
    id: 'sweet',
    type: ['All', 'Web Dev', 'Print', 'Branding'],
    src: 'SoSweet_Thumb.jpg',
    title: 'So Sweet: Case Study',
    clickable: false,
    date: 'Feb 2020',
    client: 'Personal Project',
    brief: 'Case study for a fictional bakery.',
    projDesc: 'Coming Soon',
    skills: [],
  },
]

module.exports = {
  projects,
}
